title: DITM Lab
baseurl: ""
url: "https://ditmlab.github.io"
markdown: kramdown
permalink: pretty

# Allow search engines to index this public website.
noindex: false

plugins:
  - jekyll-sitemap

exclude:
  - MAINTENANCE.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
